export const SITE_URL = "https://venomid.tools/"
export const SITE_TITLE = "Venom ID Tools"
export const SITE_DESCRIPTION = "Manage Your Venom ID(s)"
export const SITE_FULL_DESCRIPTION = "Venom IDentities (VID) serve as secure and easy-to-use domain names for managing your online presence. you can easily assign human-readable names to your blockchain and non-blockchain. VID enables these resources to be effectively managed and accessed via one, simple name."
export const SITE_CLAIM_URL = "https://venomid.network/"
export const SITE_PROFILE_URL = "https://venomid.link/"
export const VENOMSCAN_NFT = "https://testnet.venomscan.com/accounts/"
export const BTCSCAN_ADDRESS = "https://blockchair.com/bitcoin/"
export const ETHERSCAN_ADDRESS = "https://etherscan.io/address/"
export const CONTRACT_ADDRESS = "0:2787ba200fd3e45c1a4854768f69310fe4e9566383761f27936aff61ad79c8ab";
export const SOCIAL_TWITTER = "venomid_network";
export const TWITTER_URL = "https://twitter.com/";
export const GITHUB_URL = "https://github.com/samshariat/venomidapp-manage";